feat: add NeuralSpeed backend to boost up the inference speed on CPU
ollama/ollama pull request #3468
Opened 2024-04-03 00:48 UTC by ftian1

This PR is used to integrate NeuralSpeed as a new backend in Ollama to provide better performance on x86_64 platforms.
	
[NeuralSpeed](https://github.com/intel/neural-speed) is an LLM acceleration library by providing high efficient GEMM kernel and fusions on AVX/AVX2/AVX512. We can achieve better performance like [here](https://medium.com/@NeuralCompressor/llm-performance-of-intel-extension-for-transformers-f7d061556176).
	
cmd to enable NeuralSpeed backend:
```
OLLAMA_LLM_LIBRARY=nscpu_avx2 ./ollama
```

2024-06-10 20:53 UTC, atelepov approved these changes

2024-06-13 19:53 UTC, TanvirOnGH approved these changes

2024-07-11 22:04 UTC, atelepov requested changes

2024-07-11 22:04 UTC, atelepov commented on llm/generate/gen_common.sh
> +    NEURAL_SPEED_DIR=../neural_speed
Please make changes in file gen_windows.ps1 to support win build

2024-11-21 09:29 UTC, mchiang0610 commented
looks like neural speed is archived? Closing for now

2024-11-21 09:29 UTC, closed without merging