Update README.md to include ollama-r library
ollama/ollama pull request #4012
Opened 2024-04-29 01:16 UTC by hauselin

Add ollama-r library

2024-05-02 13:13 UTC, WolfTheDeveloper requested changes
There seems to be another Ollama library for R already.

2024-05-02 14:14 UTC, hauselin commented
Is it not possible to list different libraries for one programming language on the README, to provide users with more options? e.g., like how there are many overlapping web/desktop and extensions (e.g., there are multiple extensions for the Obsidian note-taking app). If not, feel free to close this issue. Thanks.

2024-05-07 16:51 UTC, jmorganca commented
Thanks for the PR! Will append it to the list for now

2024-05-07 16:51 UTC, jmorganca approved these changes

2024-05-07 16:52 UTC, merged