Set the default timeout to 600 seconds
ollama/ollama pull request #5084
Opened 2024-06-16 15:38 UTC by slavonnet

Since you have llama.cpp the default timeout is 600 seconds, then we also set 600

2024-06-16 15:41 UTC, jmorganca commented
Thank you!

2024-06-16 15:42 UTC, jmorganca approved these changes

2024-06-17 21:42 UTC, jmorganca requested changes

2024-06-17 21:42 UTC, jmorganca commented on llm/ext_server/httplib.h
> +#define CPPHTTPLIB_CONNECTION_TIMEOUT_SECOND 600
After reviewing, we shouldn't change this file as it's an http library

Instead let's change `--timeout` in https://github.com/ollama/ollama/blob/main/llm/server.go#L187

2024-06-27 12:47 UTC, slavonnet commented
I'm sorry, but I don't write in Go and I'm not ready to take on the task. I propose to divide the task into 2 parts. Part 1 - to correct the inconsistencies of values between llama.cpp and ollama. Part 2 - someone else will add a timeout option and pull the code into all parts of the code.

2024-11-22 17:55 UTC, jmorganca commented
Hi @slavonnet thanks so much again for the PR. This should be resolved now with the change to a Go-based runner – but let me know if you're still seeing it and we can revisit.

2024-11-22 17:55 UTC, closed without merging